name: Quake
version: '0.1.2'
description: Quake avec swag
author: DEMOCRAFTMC
website: https://democraft.fr
main: fr.democraft.quake.QuakePlugin
api-version: '1.20'
softdepend: [PlaceholderAPI]
commands:
  quake:
    description: Main command for Quake game
    usage: /quake <subcommand>
    permission: quake.use
    permission-message: You don't have permission to use this command!